//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.23 at 11:43:13 AM EST 
//


package gov.nih.nci.cbiit.cmps.core;

import gov.nih.nci.cbiit.cmps.ui.properties.PropertiesResult;

import java.beans.PropertyDescriptor;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for elementMeta complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="elementMeta">
 *   &lt;complexContent>
 *     &lt;extension base="{http://cmps.cbiit.nci.nih.gov/core}baseMeta">
 *       &lt;sequence>
 *         &lt;element name="attrData" type="{http://cmps.cbiit.nci.nih.gov/core}attributeMeta" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="childElement" type="{http://cmps.cbiit.nci.nih.gov/core}elementMeta" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="multiplicityIndex" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="isSimple" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isRequired" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isChoice" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isValid" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isRecursive" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isFixed" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="defaultValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="minOccurs" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="maxOccurs" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "elementMeta", propOrder = {
    "attrData",
    "childElement"
})
public class ElementMeta
    extends BaseMeta
{

    protected List<AttributeMeta> attrData;
    protected List<ElementMeta> childElement;
    @XmlAttribute
    protected BigInteger multiplicityIndex;
    @XmlAttribute
    protected Boolean isSimple;
    @XmlAttribute
    protected Boolean isRequired;
    @XmlAttribute
    protected Boolean isEnabled;
    @XmlAttribute
    protected Boolean isChoice;
    @XmlAttribute
    protected Boolean isValid;
    @XmlAttribute
    protected Boolean isRecursive;
    @XmlAttribute
    protected Boolean isFixed;
    @XmlAttribute
    protected String defaultValue;
    @XmlAttribute
    protected BigInteger minOccurs;
    @XmlAttribute
    protected BigInteger maxOccurs;

    /**
     * Gets the value of the attrData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attrData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttrData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttributeMeta }
     * 
     * 
     */
    public List<AttributeMeta> getAttrData() {
        if (attrData == null) {
            attrData = new ArrayList<AttributeMeta>();
        }
        return this.attrData;
    }

    /**
     * Gets the value of the childElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the childElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChildElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ElementMeta }
     * 
     * 
     */
    public List<ElementMeta> getChildElement() {
        if (childElement == null) {
            childElement = new ArrayList<ElementMeta>();
        }
        return this.childElement;
    }

    /**
     * Gets the value of the multiplicityIndex property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMultiplicityIndex() {
        return multiplicityIndex;
    }

    /**
     * Sets the value of the multiplicityIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMultiplicityIndex(BigInteger value) {
        this.multiplicityIndex = value;
    }

    /**
     * Gets the value of the isSimple property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsSimple() {
        return isSimple;
    }

    /**
     * Sets the value of the isSimple property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsSimple(Boolean value) {
        this.isSimple = value;
    }

    /**
     * Gets the value of the isRequired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsRequired() {
        return isRequired;
    }

    /**
     * Sets the value of the isRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsRequired(Boolean value) {
        this.isRequired = value;
    }

    /**
     * Gets the value of the isEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsEnabled() {
        return isEnabled;
    }

    /**
     * Sets the value of the isEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsEnabled(Boolean value) {
        this.isEnabled = value;
    }

    /**
     * Gets the value of the isChoice property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsChoice() {
        return isChoice;
    }

    /**
     * Sets the value of the isChoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsChoice(Boolean value) {
        this.isChoice = value;
    }

    /**
     * Gets the value of the isValid property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsValid() {
        return isValid;
    }

    /**
     * Sets the value of the isValid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsValid(Boolean value) {
        this.isValid = value;
    }

    /**
     * Gets the value of the isRecursive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsRecursive() {
        return isRecursive;
    }

    /**
     * Sets the value of the isRecursive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsRecursive(Boolean value) {
        this.isRecursive = value;
    }

    /**
     * Gets the value of the isFixed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsFixed() {
        return isFixed;
    }

    /**
     * Sets the value of the isFixed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsFixed(Boolean value) {
        this.isFixed = value;
    }

    /**
     * Gets the value of the defaultValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultValue() {
        return defaultValue;
    }

    /**
     * Sets the value of the defaultValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultValue(String value) {
        this.defaultValue = value;
    }

    /**
     * Gets the value of the minOccurs property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMinOccurs() {
        return minOccurs;
    }

    /**
     * Sets the value of the minOccurs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMinOccurs(BigInteger value) {
        this.minOccurs = value;
    }

    /**
     * Gets the value of the maxOccurs property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxOccurs() {
        return maxOccurs;
    }

    /**
     * Sets the value of the maxOccurs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxOccurs(BigInteger value) {
        this.maxOccurs = value;
    }

    public String toString()
    {
    	StringBuffer rtBuffer=new StringBuffer();
    	rtBuffer.append(getName());
    	if (getMinOccurs()==null)
    		return rtBuffer.toString();
    	
    	rtBuffer.append("["+getMinOccurs()+"...");
    	if (getMaxOccurs()!=null&&getMaxOccurs().intValue()==-1)
    		rtBuffer.append("*]");
    	else
    		rtBuffer.append(getMaxOccurs()+"]");
    	return rtBuffer.toString();
    }

	public PropertiesResult getPropertyDescriptors() throws Exception {
		Class beanClass = this.getClass();
		List<PropertyDescriptor> propList = new ArrayList<PropertyDescriptor>();
	
		propList.add(new PropertyDescriptor("Required", beanClass, "isIsRequired", null));	
		propList.add( new PropertyDescriptor("Default Value", beanClass, "getDefaultValue", null));
		propList.add(new PropertyDescriptor("minOccurs", beanClass, "getMinOccurs", null));
		propList.add(new PropertyDescriptor("maxOccurs", beanClass, "getMaxOccurs", null));
		
		PropertiesResult result = super.getPropertyDescriptors();
		result.addPropertyDescriptors(this, propList);
		return result;
	}

	public String getTitle() {
		// TODO Auto-generated method stub
		return "Element Properties";
	}
}
