//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.10 at 10:17:38 AM EDT 
//


package gov.nih.nci.cbiit.cmps.core;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for functionName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="functionName">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="constant"/>
 *     &lt;enumeration value="join"/>
 *     &lt;enumeration value="concatenate"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "functionName")
@XmlEnum
public enum FunctionName {

    @XmlEnumValue("constant")
    CONSTANT("constant"),
    @XmlEnumValue("join")
    JOIN("join"),
    @XmlEnumValue("concatenate")
    CONCATENATE("concatenate");
    private final String value;

    FunctionName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FunctionName fromValue(String v) {
        for (FunctionName c: FunctionName.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
