/*L
 * Copyright SAIC, SAIC-Frederick.
 *
 * Distributed under the OSI-approved BSD 3-Clause License.
 * See http://ncip.github.com/caadapter/LICENSE.txt for details.
 */

/**





 */


package gov.nih.nci.caadapter.common.csv;

import gov.nih.nci.caadapter.common.MetaException;

/**
 * An interface that allows csv metadata to be autogenerated from disparate data sources.
 *
 * @author OWNER: Matthew Giordano
 * @author LAST UPDATE $Author: phadkes $
 * @since     caAdapter v1.2
 * @version    $Revision: 1.3 $
 * @date        $Date: 2008-09-24 20:52:36 $
 */

public interface CSVMetaGeneratorUtil {
    public CSVMetaResult getMetadata()throws MetaException;
}

/**
 * HISTORY      : $Log: not supported by cvs2svn $
*/
